export const projectProfiles = [
  {
    slug: 'page-arizona-custom-residence',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-09-30',
    title: 'Page Custom Residence',
    projectType: 'Custom Home',
    category: 'custom-home',
    serviceSlug: 'custom-home-plans',
    locationLabel: 'Arizona',
    squareFeet: '2,381 sq ft total living area',
    summary: 'A multi-level residence coordinated from the primary floor plan through sections, construction details, electrical, and plumbing layouts.',
    challenge: 'Develop a complete residential drawing set that coordinated the home layout with the systems and details needed behind the walls.',
    approach: 'TDD carried the same residential layout through architectural drawings, building sections, construction details, electrical planning, and water-supply planning.',
    deliverables: ['Floor plans', 'Building sections', 'Construction details', 'Electrical plans', 'Water-supply plans and piping schematic'],
    result: 'The resulting drawing package gives the owner and field teams a coordinated reference for design review and construction planning.',
    measurementContext: 'Area is the total living area stated on the source plan; it is not presented as independently verified heated or conditioned area.',
    images: [
      { src: '/project-assets/custom-home-render-front.webp', alt: 'Front design visualization of an Arizona custom residence', caption: 'Front design visualization - concept, not finished construction', approved: true },
      { src: '/project-assets/custom-home-render-rear.webp', alt: 'Rear terrace design visualization of an Arizona custom residence', caption: 'Rear terrace design visualization', approved: true },
      { src: '/project-assets/custom-home-plan.webp', alt: 'Cropped main floor plan for an Arizona custom residence', caption: 'Primary floor-plan coordination', approved: true },
      { src: '/project-assets/custom-home-section.webp', alt: 'Cropped building section for an Arizona custom residence', caption: 'Building section', approved: true },
      { src: '/project-assets/construction-details.webp', alt: 'Cropped residential construction-detail sheet', caption: 'Construction details', approved: true },
      { src: '/project-assets/electrical-plan.webp', alt: 'Cropped residential electrical plan with lighting and switching layouts', caption: 'Electrical planning', approved: true },
      { src: '/project-assets/plumbing-plan.webp', alt: 'Cropped residential water-supply plan', caption: 'Water-supply planning', approved: true },
      { src: '/project-assets/plumbing-schematic.webp', alt: 'Cropped residential water-piping schematic', caption: 'Water-piping schematic', approved: true },
    ],
  },
  {
    slug: 'arizona-whole-home-remodel',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-09-30',
    title: 'Arizona Whole-Home Remodel',
    projectType: 'Remodel',
    category: 'remodel',
    serviceSlug: 'remodel-as-built-drawings',
    locationLabel: 'Arizona',
    squareFeet: 'Whole-home remodel planning',
    summary: 'Existing and proposed plans make a substantial residential remodel legible before work begins.',
    challenge: 'Clearly distinguish demolition work from the proposed layout across a large existing residence without losing the relationship between old and new conditions.',
    approach: 'TDD paired a demolition plan with a proposed floor plan and supporting building section so openings, circulation, rooms, and exterior living areas could be reviewed together.',
    deliverables: ['Demolition plan', 'Proposed floor plan', 'Supporting building section'],
    result: 'The paired drawings provide a direct before-and-proposed record for project coordination and scope conversations.',
    measurementContext: 'The source set states the area of the existing building; this profile does not present that figure as the remodel scope.',
    images: [
      { src: '/project-assets/remodel-existing-photo.webp', alt: 'Existing-condition exterior photograph for an Arizona residential remodel', caption: 'Existing condition - not a finished-project photograph', approved: true },
      { src: '/project-assets/remodel-existing-plan.webp', alt: 'Cropped demolition plan for an Arizona residential remodel', caption: 'Demolition and opening plan', approved: true },
      { src: '/project-assets/remodel-plan.webp', alt: 'Cropped proposed floor plan for an Arizona residential remodel', caption: 'Proposed layout', approved: true },
      { src: '/project-assets/remodel-section.webp', alt: 'Cropped building section supporting an Arizona remodel', caption: 'Supporting section', approved: true },
    ],
  },
  {
    slug: 'farmhouse-design-visualization',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-10-01',
    title: 'Farmhouse Design Visualization',
    projectType: 'Custom Home Visualization',
    category: 'custom-home',
    serviceSlug: 'custom-home-plans',
    locationLabel: 'Location withheld',
    squareFeet: 'Private residential project',
    summary: 'A walk-through-ready farmhouse model showing the exterior form, covered outdoor spaces, and key interiors before construction.',
    challenge: 'Make the proposed home easy to understand beyond the plan set, including its exterior massing, room flow, and early finish direction.',
    approach: 'TDD developed a navigable residential model and composed exterior and interior views so the design could be reviewed from the front porch through the primary living spaces.',
    deliverables: ['Interactive 3D model', 'Exterior design visualizations', 'Interior room views', 'Walk-through-ready model'],
    result: 'The model gives the homeowner and project team a shared visual reference for discussing the design before decisions reach the field.',
    measurementContext: 'Design-stage visualization of a private residential project. Client identity and exact location are withheld; images are not finished-construction photography.',
    images: [
      { src: '/project-assets/farmhouse-render-front.webp', alt: 'Front three-quarter design visualization of a single-story farmhouse with a full-width covered porch', caption: 'Front exterior visualization — proposed design', approved: true },
      { src: '/project-assets/farmhouse-render-rear-porch.webp', alt: 'Rear three-quarter design visualization of a farmhouse with a covered patio', caption: 'Rear covered-patio visualization', approved: true },
      { src: '/project-assets/farmhouse-render-kitchen.webp', alt: 'Interior design visualization of a farmhouse kitchen with island and pendant lighting', caption: 'Kitchen and island visualization', approved: true },
      { src: '/project-assets/farmhouse-render-living-room.webp', alt: 'Interior design visualization of the farmhouse living room and adjacent bedroom doorway', caption: 'Living-room visualization', approved: true },
      { src: '/project-assets/farmhouse-render-primary-bedroom.webp', alt: 'Interior design visualization of the farmhouse primary bedroom', caption: 'Primary-bedroom visualization', approved: true },
    ],
  },
  {
    slug: 'three-bedroom-barndominium-study',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-09-30',
    title: 'Three-Bedroom Barndominium Study',
    projectType: 'Barndominium',
    category: 'barndominium-shop',
    serviceSlug: 'barndominium-plans',
    locationLabel: 'Location withheld',
    squareFeet: 'Design-stage residence',
    summary: 'A single-story barndominium study pairing residential space with generous covered outdoor and vehicle areas.',
    challenge: 'Organize a wide, single-level plan so the living areas, bedrooms, covered spaces, and vehicle access read as one coherent building.',
    approach: 'TDD developed the floor-plan study alongside front and rear elevations to coordinate the residential layout with the exterior form.',
    deliverables: ['Floor-plan study', 'Front elevation', 'Rear elevation'],
    result: 'The design-stage sheets provide a coordinated basis for owner review and further project development.',
    measurementContext: 'This is proposed design imagery, not a completed building, permit approval, or a complete construction package.',
    images: [
      { src: '/project-assets/barndominium-elevations.webp', alt: 'Front and rear elevations for a proposed barndominium', caption: 'Proposed front and rear elevations', approved: true },
      { src: '/project-assets/barndominium-floor-plan.webp', alt: 'Floor-plan study for a three-bedroom barndominium', caption: 'Design-stage floor plan', approved: true },
    ],
  },
  {
    slug: 'steel-shop-barn-study',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-09-30',
    title: 'Steel Shop and Barn Study',
    projectType: 'Shop / Barn',
    category: 'barndominium-shop',
    serviceSlug: 'barndominium-plans',
    locationLabel: 'Location withheld',
    squareFeet: '3,000 sq ft proposed shop',
    summary: 'A proposed 50-by-60-foot steel shop organized for open work space, vehicle access, lighting, and a straightforward exterior shell.',
    challenge: 'Coordinate a large open shop with multiple overhead doors, useful lighting coverage, and clear exterior elevations.',
    approach: 'TDD paired the open floor plan with four exterior elevations to communicate the building envelope and access points.',
    deliverables: ['Shop floor plan', 'Lighting and electrical layout', 'Four exterior elevations'],
    result: 'The proposed sheets create a clear design reference for continued coordination of the shop project.',
    measurementContext: 'Dimensions and area are stated on the source drawings; this profile does not claim construction, permit approval, or engineering completeness.',
    images: [
      { src: '/project-assets/steel-shop-elevations.webp', alt: 'Four exterior elevations for a proposed steel shop and barn', caption: 'Proposed exterior elevations', approved: true },
      { src: '/project-assets/steel-shop-floor-plan.webp', alt: 'Open floor plan and electrical layout for a proposed steel shop', caption: 'Open shop plan and lighting layout', approved: true },
    ],
  },
  {
    slug: 'utah-detached-garage',
    enabled: true,
    editorialApproved: true,
    clientMediaApproved: true,
    reviewedDate: '2026-09-30',
    title: 'Utah Detached Garage',
    projectType: 'Garage',
    category: 'garage-addition',
    serviceSlug: 'garage-adu-addition-plans',
    locationLabel: 'Utah',
    squareFeet: '720 sq ft garage area',
    summary: 'A compact detached-garage drawing set showing coordinated exterior elevations and a building section.',
    challenge: 'Document a straightforward accessory structure with enough exterior and sectional information to communicate its form and construction intent.',
    approach: 'TDD assembled multiple exterior elevations with a cross section and focused wall detail on a single coordinated sheet.',
    deliverables: ['Exterior elevations', 'Building cross section', 'Wall and foundation detail'],
    result: 'The sheet gives the project team a compact visual reference for the garage exterior and building assembly.',
    measurementContext: 'The 720 sq ft figure is the detached-garage area stated in the source set, not living or heated area.',
    images: [
      { src: '/project-assets/garage-elevations.webp', alt: 'Cropped exterior elevations and section for a Utah detached garage', caption: 'Elevations and building section', approved: true },
    ],
  },
];
